repos:

  # commit messages
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.1.1

  # commit lint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  # rust language
  - hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
    repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0

  # text and yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      - id: end-of-file-fixer

      - id: check-yaml

      - id: check-added-large-files
        args: ['--maxkb=10000']

      - id: mixed-line-ending
        exclude: ^.tests/
        args: [--fix=lf]

      - id: detect-private-key

  # markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        args: [--config=.github/markdown_lint.yaml]
