repos:

  # # rust language
  # - repo: https://github.com/doublify/pre-commit-rust
  #   rev: v1.0
  #   hooks:
  #     - id: fmt
  #     - id: cargo-check
  #     - id: clippy

  # text and yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      - id: end-of-file-fixer

      - id: check-yaml

      - id: check-added-large-files
        args: ['--maxkb=10000']

      - id: mixed-line-ending
        exclude: ^.tests/
        args: [--fix=lf]

      - id: detect-private-key

  # markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        args: [--config=.github/markdown_lint.yaml]
